# Generated by Django 5.0.2 on 2024-03-22 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='List_Of_Users',
        ),
    ]
