# Generated by Django 5.0.2 on 2024-03-22 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0002_rename_user_list_of_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('feedback', models.TextField()),
            ],
        ),
    ]
